method: requests
query:
#  - 'dipirona'
#  - 'pomada'
#  - 'gripe'
#  - 'paracetamol'
  - 'fralda'
  - 'protetor'
  - 'vitamina'
#  - 'soro'
#  - 'leite'
#  - 'suplemento'
#  - 'creme'
#  - 'condicionador'
#  - 'pet'
#  - 'sabonete'
#  - 'fita'
#  - 'dor'
#  - 'febre'